@BusinessAPI_HostAddress = http://localhost:5080


###
POST {{BusinessAPI_HostAddress}}/Index HTTP/1.1
Content-Type: application/x-www-form-urlencoded

FormId=AddLocation&AddLocationForm.Label=TestLocation&AddLocationForm.XCoord=123&AddLocationForm.YCoord=456&AddLocationForm.Space=100
