@BusinessAPI_HostAddress = http://localhost:5080


###
POST {{BusinessAPI_HostAddress}}/add-location HTTP/1.1
Content-Type: application/x-www-form-urlencoded
label=NewYork&xCoord=40&yCoord=40&space=40
